filters = [["cloud_base_height", "Cloud base height"], ["high_cloud_cover", "High cloud cover"],
           ["low_cloud_cover", "Low cloud cover"], ["medium_cloud_cover", "Medium cloud cover"],
           ["total_cloud_cover", "Total cloud cover"], ["total_column_cloud_ice_water", "Total column cloud ice water"],
           ["total_column_cloud_liquid_water", "Total column cloud liquid water"],
           ["vertical_integral_of_divergence_of_cloud_frozen_water_flux",
            "Vertical integral of divergence of cloud frozen water flux"],
           ["vertical_integral_of_divergence_of_cloud_liquid_water_flux",
            "Vertical integral of divergence of cloud liquid water flux"],
           ["vertical_integral_of_eastward_cloud_frozen_water_flux",
            "Vertical integral of eastward cloud frozen water flux"],
           ["vertical_integral_of_eastward_cloud_liquid_water_flux",
            "Vertical integral of eastward cloud liquid water flux"],
           ["vertical_integral_of_northward_cloud_frozen_water_flux",
            "Vertical integral of northward cloud frozen water flux"],
           ["vertical_integral_of_northward_cloud_liquid_water_flux",
            "Vertical integral of northward cloud liquid water flux"]]
