filters = [["air_density_over_the_oceans", "Air density over the oceans"],
           ["altimeter_corrected_wave_height", "Altimeter corrected wave height"],
           ["altimeter_wave_height", "Altimeter wave height"],
           ["coefficient_of_drag_with_waves", "Coefficient of drag with waves"],
           ["free_convective_velocity_over_the_oceans", "Free convective velocity over the oceans"],
           ["maximum_individual_wave_height", "Maximum individual wave height"],
           ["mean_direction_of_total_swell", "Mean direction of total swell"],
           ["mean_direction_of_wind_waves", "Mean direction of wind waves"],
           ["mean_period_of_total_swell", "Mean period of total swell"],
           ["mean_period_of_wind_waves", "Mean period of wind waves"],
           ["mean_square_slope_of_waves", "Mean square slope of waves"], ["mean_wave_direction", "Mean wave direction"],
           ["mean_wave_direction_of_first_swell_partition", "Mean wave direction of first swell partition"],
           ["mean_wave_direction_of_second_swell_partition", "Mean wave direction of second swell partition"],
           ["mean_wave_direction_of_third_swell_partition", "Mean wave direction of third swell partition"],
           ["mean_wave_period", "Mean wave period"],
           ["mean_wave_period_based_on_first_moment", "Mean wave period based on first moment"],
           ["mean_wave_period_based_on_first_moment_for_swell", "Mean wave period based on first moment for swell"],
           ["mean_wave_period_based_on_first_moment_for_wind_waves",
            "Mean wave period based on first moment for wind waves"],
           ["mean_wave_period_based_on_second_moment_for_swell", "Mean wave period based on second moment for swell"],
           ["mean_wave_period_based_on_second_moment_for_wind_waves",
            "Mean wave period based on second moment for wind waves"],
           ["mean_wave_period_of_first_swell_partition", "Mean wave period of first swell partition"],
           ["mean_wave_period_of_second_swell_partition", "Mean wave period of second swell partition"],
           ["mean_wave_period_of_third_swell_partition", "Mean wave period of third swell partition"],
           ["mean_zero_crossing_wave_period", "Mean zero crossing wave period"],
           ["normalized_energy_flux_into_ocean", "Normalized energy flux into ocean"],
           ["normalized_energy_flux_into_waves", "Normalized energy flux into waves"],
           ["normalized_stress_into_ocean", "Normalized stress into ocean"],
           ["ocean_surface_stress_equivalent_10m_neutral_wind_direction",
            "Ocean surface stress equivalent 10m neutral wind direction"],
           ["ocean_surface_stress_equivalent_10m_neutral_wind_speed",
            "Ocean surface stress equivalent 10m neutral wind speed"], ["peak_wave_period", "Peak wave period"],
           ["period_corresponding_to_maximum_individual_wave_height",
            "Period corresponding to maximum individual wave height"],
           ["significant_height_of_combined_wind_waves_and_swell",
            "Significant height of combined wind waves and swell"],
           ["significant_height_of_total_swell", "Significant height of total swell"],
           ["significant_height_of_wind_waves", "Significant height of wind waves"],
           ["significant_wave_height_of_first_swell_partition", "Significant wave height of first swell partition"],
           ["significant_wave_height_of_second_swell_partition", "Significant wave height of second swell partition"],
           ["significant_wave_height_of_third_swell_partition", "Significant wave height of third swell partition"],
           ["wave_spectral_directional_width", "Wave spectral directional width"],
           ["wave_spectral_directional_width_for_swell", "Wave spectral directional width for swell"],
           ["wave_spectral_directional_width_for_wind_waves", "Wave spectral directional width for wind waves"],
           ["wave_spectral_kurtosis", "Wave spectral kurtosis"],
           ["wave_spectral_peakedness", "Wave spectral peakedness"],
           ["wave_spectral_skewness", "Wave spectral skewness"]]
