# Generated by Django 2.2.1 on 2019-05-15 20:19

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('json_content', jsonfield.fields.JSONField()),
                ('status', models.TextField(default='pending')),
            ],
        ),
    ]
