# Generated by Django 2.2.1 on 2019-05-25 15:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('json_content', jsonfield.fields.JSONField()),
                ('status', models.TextField(default='pending')),
                ('data_set', models.TextField(default='???', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('path', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=31)),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloader.Task')),
            ],
        ),
    ]
