# Generated by Django 2.2.1 on 2019-05-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='error_msg',
            field=models.TextField(default='no error'),
        ),
    ]
