# Generated by Django 2.2.1 on 2019-05-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_request_error_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='error_msg',
        ),
        migrations.AddField(
            model_name='request',
            name='msg',
            field=models.TextField(default='success'),
        ),
    ]
