# Generated by Django 2.2.1 on 2019-05-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_auto_20190524_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='msg',
            field=models.TextField(),
        ),
    ]
