filters = [["100m_u_component_of_wind", "100m u component of wind"],
           ["100m_v_component_of_wind", "100m v component of wind"],
           ["10m_u_component_of_neutral_wind", "10m u component of neutral wind"],
           ["10m_u_component_of_wind", "10m u component of wind"],
           ["10m_v_component_of_neutral_wind", "10m v component of neutral wind"],
           ["10m_v_component_of_wind", "10m v component of wind"],
           ["10m_wind_gust_since_previous_post_processing", "10m wind gust since previous post processing"],
           ["2m_dewpoint_temperature", "2m dewpoint temperature"], ["2m_temperature", "2m temperature"],
           ["air_density_over_the_oceans", "Air density over the oceans"],
           ["altimeter_corrected_wave_height", "Altimeter corrected wave height"],
           ["altimeter_range_relative_correction", "Altimeter range relative correction"],
           ["altimeter_wave_height", "Altimeter wave height"],
           ["angle_of_sub_gridscale_orography", "Angle of sub gridscale orography"],
           ["anisotropy_of_sub_gridscale_orography", "Anisotropy of sub gridscale orography"],
           ["benjamin_feir_index", "Benjamin feir index"], ["boundary_layer_dissipation", "Boundary layer dissipation"],
           ["boundary_layer_height", "Boundary layer height"], ["charnock", "Charnock"],
           ["clear_sky_direct_solar_radiation_at_surface", "Clear sky direct solar radiation at surface"],
           ["cloud_base_height", "Cloud base height"],
           ["coefficient_of_drag_with_waves", "Coefficient of drag with waves"],
           ["convective_available_potential_energy", "Convective available potential energy"],
           ["convective_inhibition", "Convective inhibition"], ["convective_precipitation", "Convective precipitation"],
           ["convective_rain_rate", "Convective rain rate"], ["convective_snowfall", "Convective snowfall"],
           ["convective_snowfall_rate_water_equivalent", "Convective snowfall rate water equivalent"],
           ["downward_uv_radiation_at_the_surface", "Downward uv radiation at the surface"],
           ["duct_base_height", "Duct base height"],
           ["eastward_gravity_wave_surface_stress", "Eastward gravity wave surface stress"],
           ["eastward_turbulent_surface_stress", "Eastward turbulent surface stress"], ["evaporation", "Evaporation"],
           ["forecast_albedo", "Forecast albedo"],
           ["forecast_logarithm_of_surface_roughness_for_heat", "Forecast logarithm of surface roughness for heat"],
           ["forecast_surface_roughness", "Forecast surface roughness"],
           ["free_convective_velocity_over_the_oceans", "Free convective velocity over the oceans"],
           ["friction_velocity", "Friction velocity"], ["gravity_wave_dissipation", "Gravity wave dissipation"],
           ["high_cloud_cover", "High cloud cover"], ["high_vegetation_cover", "High vegetation cover"],
           ["ice_temperature_layer_1", "Ice temperature layer 1"],
           ["ice_temperature_layer_2", "Ice temperature layer 2"],
           ["ice_temperature_layer_3", "Ice temperature layer 3"],
           ["ice_temperature_layer_4", "Ice temperature layer 4"],
           ["instantaneous_10m_wind_gust", "Instantaneous 10m wind gust"],
           ["instantaneous_eastward_turbulent_surface_stress", "Instantaneous eastward turbulent surface stress"],
           ["instantaneous_large_scale_surface_precipitation_fraction",
            "Instantaneous large scale surface precipitation fraction"],
           ["instantaneous_moisture_flux", "Instantaneous moisture flux"],
           ["instantaneous_northward_turbulent_surface_stress", "Instantaneous northward turbulent surface stress"],
           ["instantaneous_surface_sensible_heat_flux", "Instantaneous surface sensible heat flux"],
           ["k_index", "K index"],
           ["lake_bottom_temperature", "Lake bottom temperature"], ["lake_cover", "Lake cover"],
           ["lake_depth", "Lake depth"],
           ["lake_ice_depth", "Lake ice depth"], ["lake_ice_temperature", "Lake ice temperature"],
           ["lake_mix_layer_depth", "Lake mix layer depth"],
           ["lake_mix_layer_temperature", "Lake mix layer temperature"],
           ["lake_shape_factor", "Lake shape factor"], ["lake_total_layer_temperature", "Lake total layer temperature"],
           ["land_sea_mask", "Land sea mask"], ["large_scale_precipitation", "Large scale precipitation"],
           ["large_scale_precipitation_fraction", "Large scale precipitation fraction"],
           ["large_scale_rain_rate", "Large scale rain rate"], ["large_scale_snowfall", "Large scale snowfall"],
           ["large_scale_snowfall_rate_water_equivalent", "Large scale snowfall rate water equivalent"],
           ["leaf_area_index_high_vegetation", "Leaf area index high vegetation"],
           ["leaf_area_index_low_vegetation", "Leaf area index low vegetation"], ["low_cloud_cover", "Low cloud cover"],
           ["low_vegetation_cover", "Low vegetation cover"],
           ["maximum_2m_temperature_since_previous_post_processing",
            "Maximum 2m temperature since previous post processing"],
           ["maximum_individual_wave_height", "Maximum individual wave height"],
           ["maximum_total_precipitation_rate_since_previous_post_processing",
            "Maximum total precipitation rate since previous post processing"],
           ["mean_boundary_layer_dissipation", "Mean boundary layer dissipation"],
           ["mean_convective_precipitation_rate", "Mean convective precipitation rate"],
           ["mean_convective_snowfall_rate", "Mean convective snowfall rate"],
           ["mean_direction_of_total_swell", "Mean direction of total swell"],
           ["mean_direction_of_wind_waves", "Mean direction of wind waves"],
           ["mean_eastward_gravity_wave_surface_stress", "Mean eastward gravity wave surface stress"],
           ["mean_eastward_turbulent_surface_stress", "Mean eastward turbulent surface stress"],
           ["mean_evaporation_rate", "Mean evaporation rate"],
           ["mean_gravity_wave_dissipation", "Mean gravity wave dissipation"],
           ["mean_large_scale_precipitation_fraction", "Mean large scale precipitation fraction"],
           ["mean_large_scale_precipitation_rate", "Mean large scale precipitation rate"],
           ["mean_large_scale_snowfall_rate", "Mean large scale snowfall rate"],
           ["mean_northward_gravity_wave_surface_stress", "Mean northward gravity wave surface stress"],
           ["mean_northward_turbulent_surface_stress", "Mean northward turbulent surface stress"],
           ["mean_period_of_total_swell", "Mean period of total swell"],
           ["mean_period_of_wind_waves", "Mean period of wind waves"],
           ["mean_potential_evaporation_rate", "Mean potential evaporation rate"],
           ["mean_runoff_rate", "Mean runoff rate"],
           ["mean_sea_level_pressure", "Mean sea level pressure"],
           ["mean_snow_evaporation_rate", "Mean snow evaporation rate"],
           ["mean_snowfall_rate", "Mean snowfall rate"], ["mean_snowmelt_rate", "Mean snowmelt rate"],
           ["mean_square_slope_of_waves", "Mean square slope of waves"],
           ["mean_sub_surface_runoff_rate", "Mean sub surface runoff rate"],
           ["mean_surface_direct_short_wave_radiation_flux", "Mean surface direct short wave radiation flux"],
           ["mean_surface_direct_short_wave_radiation_flux_clear_sky",
            "Mean surface direct short wave radiation flux clear sky"],
           ["mean_surface_downward_long_wave_radiation_flux", "Mean surface downward long wave radiation flux"],
           ["mean_surface_downward_long_wave_radiation_flux_clear_sky",
            "Mean surface downward long wave radiation flux clear sky"],
           ["mean_surface_downward_short_wave_radiation_flux", "Mean surface downward short wave radiation flux"],
           ["mean_surface_downward_short_wave_radiation_flux_clear_sky",
            "Mean surface downward short wave radiation flux clear sky"],
           ["mean_surface_downward_uv_radiation_flux", "Mean surface downward uv radiation flux"],
           ["mean_surface_latent_heat_flux", "Mean surface latent heat flux"],
           ["mean_surface_net_long_wave_radiation_flux", "Mean surface net long wave radiation flux"],
           ["mean_surface_net_long_wave_radiation_flux_clear_sky",
            "Mean surface net long wave radiation flux clear sky"],
           ["mean_surface_net_short_wave_radiation_flux", "Mean surface net short wave radiation flux"],
           ["mean_surface_net_short_wave_radiation_flux_clear_sky",
            "Mean surface net short wave radiation flux clear sky"],
           ["mean_surface_runoff_rate", "Mean surface runoff rate"],
           ["mean_surface_sensible_heat_flux", "Mean surface sensible heat flux"],
           ["mean_top_downward_short_wave_radiation_flux", "Mean top downward short wave radiation flux"],
           ["mean_top_net_long_wave_radiation_flux", "Mean top net long wave radiation flux"],
           ["mean_top_net_long_wave_radiation_flux_clear_sky", "Mean top net long wave radiation flux clear sky"],
           ["mean_top_net_short_wave_radiation_flux", "Mean top net short wave radiation flux"],
           ["mean_top_net_short_wave_radiation_flux_clear_sky", "Mean top net short wave radiation flux clear sky"],
           ["mean_total_precipitation_rate", "Mean total precipitation rate"],
           ["mean_vertical_gradient_of_refractivity_inside_trapping_layer",
            "Mean vertical gradient of refractivity inside trapping layer"],
           ["mean_vertically_integrated_moisture_divergence", "Mean vertically integrated moisture divergence"],
           ["mean_wave_direction", "Mean wave direction"],
           ["mean_wave_direction_of_first_swell_partition", "Mean wave direction of first swell partition"],
           ["mean_wave_direction_of_second_swell_partition", "Mean wave direction of second swell partition"],
           ["mean_wave_direction_of_third_swell_partition", "Mean wave direction of third swell partition"],
           ["mean_wave_period", "Mean wave period"],
           ["mean_wave_period_based_on_first_moment", "Mean wave period based on first moment"],
           ["mean_wave_period_based_on_first_moment_for_swell", "Mean wave period based on first moment for swell"],
           ["mean_wave_period_based_on_first_moment_for_wind_waves",
            "Mean wave period based on first moment for wind waves"],
           ["mean_wave_period_based_on_second_moment_for_swell", "Mean wave period based on second moment for swell"],
           ["mean_wave_period_based_on_second_moment_for_wind_waves",
            "Mean wave period based on second moment for wind waves"],
           ["mean_wave_period_of_first_swell_partition", "Mean wave period of first swell partition"],
           ["mean_wave_period_of_second_swell_partition", "Mean wave period of second swell partition"],
           ["mean_wave_period_of_third_swell_partition", "Mean wave period of third swell partition"],
           ["mean_zero_crossing_wave_period", "Mean zero crossing wave period"],
           ["medium_cloud_cover", "Medium cloud cover"],
           ["minimum_2m_temperature_since_previous_post_processing",
            "Minimum 2m temperature since previous post processing"],
           ["minimum_total_precipitation_rate_since_previous_post_processing",
            "Minimum total precipitation rate since previous post processing"],
           ["minimum_vertical_gradient_of_refractivity_inside_trapping_layer",
            "Minimum vertical gradient of refractivity inside trapping layer"],
           ["model_bathymetry", "Model bathymetry"],
           ["near_ir_albedo_for_diffuse_radiation", "Near ir albedo for diffuse radiation"],
           ["near_ir_albedo_for_direct_radiation", "Near ir albedo for direct radiation"],
           ["normalized_energy_flux_into_ocean", "Normalized energy flux into ocean"],
           ["normalized_energy_flux_into_waves", "Normalized energy flux into waves"],
           ["normalized_stress_into_ocean", "Normalized stress into ocean"],
           ["northward_gravity_wave_surface_stress", "Northward gravity wave surface stress"],
           ["northward_turbulent_surface_stress", "Northward turbulent surface stress"],
           ["ocean_surface_stress_equivalent_10m_neutral_wind_direction",
            "Ocean surface stress equivalent 10m neutral wind direction"],
           ["ocean_surface_stress_equivalent_10m_neutral_wind_speed",
            "Ocean surface stress equivalent 10m neutral wind speed"],
           ["orography", "Orography"], ["peak_wave_period", "Peak wave period"],
           ["period_corresponding_to_maximum_individual_wave_height",
            "Period corresponding to maximum individual wave height"],
           ["potential_evaporation", "Potential evaporation"], ["precipitation_type", "Precipitation type"],
           ["runoff", "Runoff"],
           ["sea_ice_cover", "Sea ice cover"], ["sea_surface_temperature", "Sea surface temperature"],
           ["significant_height_of_combined_wind_waves_and_swell",
            "Significant height of combined wind waves and swell"],
           ["significant_height_of_total_swell", "Significant height of total swell"],
           ["significant_height_of_wind_waves", "Significant height of wind waves"],
           ["significant_wave_height_of_first_swell_partition", "Significant wave height of first swell partition"],
           ["significant_wave_height_of_second_swell_partition", "Significant wave height of second swell partition"],
           ["significant_wave_height_of_third_swell_partition", "Significant wave height of third swell partition"],
           ["skin_reservoir_content", "Skin reservoir content"], ["skin_temperature", "Skin temperature"],
           ["slope_of_sub_gridscale_orography", "Slope of sub gridscale orography"], ["snow_albedo", "Snow albedo"],
           ["snow_density", "Snow density"], ["snow_depth", "Snow depth"], ["snow_evaporation", "Snow evaporation"],
           ["snowfall", "Snowfall"], ["snowmelt", "Snowmelt"], ["soil_temperature_level_1", "Soil temperature level 1"],
           ["soil_temperature_level_2", "Soil temperature level 2"],
           ["soil_temperature_level_3", "Soil temperature level 3"],
           ["soil_temperature_level_4", "Soil temperature level 4"], ["soil_type", "Soil type"],
           ["standard_deviation_of_filtered_subgrid_orography", "Standard deviation of filtered subgrid orography"],
           ["standard_deviation_of_orography", "Standard deviation of orography"],
           ["sub_surface_runoff", "Sub surface runoff"],
           ["surface_latent_heat_flux", "Surface latent heat flux"],
           ["surface_net_solar_radiation", "Surface net solar radiation"],
           ["surface_net_solar_radiation_clear_sky", "Surface net solar radiation clear sky"],
           ["surface_net_thermal_radiation", "Surface net thermal radiation"],
           ["surface_net_thermal_radiation_clear_sky", "Surface net thermal radiation clear sky"],
           ["surface_pressure", "Surface pressure"], ["surface_runoff", "Surface runoff"],
           ["surface_sensible_heat_flux", "Surface sensible heat flux"],
           ["surface_solar_radiation_downward_clear_sky", "Surface solar radiation downward clear sky"],
           ["surface_solar_radiation_downwards", "Surface solar radiation downwards"],
           ["surface_thermal_radiation_downward_clear_sky", "Surface thermal radiation downward clear sky"],
           ["surface_thermal_radiation_downwards", "Surface thermal radiation downwards"],
           ["temperature_of_snow_layer", "Temperature of snow layer"],
           ["toa_incident_solar_radiation", "Toa incident solar radiation"],
           ["top_net_solar_radiation", "Top net solar radiation"],
           ["top_net_solar_radiation_clear_sky", "Top net solar radiation clear sky"],
           ["top_net_thermal_radiation", "Top net thermal radiation"],
           ["top_net_thermal_radiation_clear_sky", "Top net thermal radiation clear sky"],
           ["total_cloud_cover", "Total cloud cover"], ["total_column_cloud_ice_water", "Total column cloud ice water"],
           ["total_column_cloud_liquid_water", "Total column cloud liquid water"],
           ["total_column_ozone", "Total column ozone"],
           ["total_column_rain_water", "Total column rain water"],
           ["total_column_snow_water", "Total column snow water"],
           ["total_column_supercooled_liquid_water", "Total column supercooled liquid water"],
           ["total_column_water", "Total column water"], ["total_column_water_vapour", "Total column water vapour"],
           ["total_precipitation", "Total precipitation"],
           ["total_sky_direct_solar_radiation_at_surface", "Total sky direct solar radiation at surface"],
           ["total_totals_index", "Total totals index"], ["trapping_layer_base_height", "Trapping layer base height"],
           ["trapping_layer_top_height", "Trapping layer top height"],
           ["type_of_high_vegetation", "Type of high vegetation"],
           ["type_of_low_vegetation", "Type of low vegetation"],
           ["u_component_stokes_drift", "U component stokes drift"],
           ["uv_visible_albedo_for_diffuse_radiation", "Uv visible albedo for diffuse radiation"],
           ["uv_visible_albedo_for_direct_radiation", "Uv visible albedo for direct radiation"],
           ["v_component_stokes_drift", "V component stokes drift"],
           ["vertical_integral_of_divergence_of_cloud_frozen_water_flux",
            "Vertical integral of divergence of cloud frozen water flux"],
           ["vertical_integral_of_divergence_of_cloud_liquid_water_flux",
            "Vertical integral of divergence of cloud liquid water flux"],
           ["vertical_integral_of_divergence_of_geopotential_flux",
            "Vertical integral of divergence of geopotential flux"],
           ["vertical_integral_of_divergence_of_kinetic_energy_flux",
            "Vertical integral of divergence of kinetic energy flux"],
           ["vertical_integral_of_divergence_of_mass_flux", "Vertical integral of divergence of mass flux"],
           ["vertical_integral_of_divergence_of_moisture_flux", "Vertical integral of divergence of moisture flux"],
           ["vertical_integral_of_divergence_of_ozone_flux", "Vertical integral of divergence of ozone flux"],
           ["vertical_integral_of_divergence_of_thermal_energy_flux",
            "Vertical integral of divergence of thermal energy flux"],
           ["vertical_integral_of_divergence_of_total_energy_flux",
            "Vertical integral of divergence of total energy flux"],
           ["vertical_integral_of_eastward_cloud_frozen_water_flux",
            "Vertical integral of eastward cloud frozen water flux"],
           ["vertical_integral_of_eastward_cloud_liquid_water_flux",
            "Vertical integral of eastward cloud liquid water flux"],
           ["vertical_integral_of_eastward_geopotential_flux", "Vertical integral of eastward geopotential flux"],
           ["vertical_integral_of_eastward_heat_flux", "Vertical integral of eastward heat flux"],
           ["vertical_integral_of_eastward_kinetic_energy_flux", "Vertical integral of eastward kinetic energy flux"],
           ["vertical_integral_of_eastward_mass_flux", "Vertical integral of eastward mass flux"],
           ["vertical_integral_of_eastward_ozone_flux", "Vertical integral of eastward ozone flux"],
           ["vertical_integral_of_eastward_total_energy_flux", "Vertical integral of eastward total energy flux"],
           ["vertical_integral_of_eastward_water_vapour_flux", "Vertical integral of eastward water vapour flux"],
           ["vertical_integral_of_energy_conversion", "Vertical integral of energy conversion"],
           ["vertical_integral_of_kinetic_energy", "Vertical integral of kinetic energy"],
           ["vertical_integral_of_mass_of_atmosphere", "Vertical integral of mass of atmosphere"],
           ["vertical_integral_of_mass_tendency", "Vertical integral of mass tendency"],
           ["vertical_integral_of_northward_cloud_frozen_water_flux",
            "Vertical integral of northward cloud frozen water flux"],
           ["vertical_integral_of_northward_cloud_liquid_water_flux",
            "Vertical integral of northward cloud liquid water flux"],
           ["vertical_integral_of_northward_geopotential_flux", "Vertical integral of northward geopotential flux"],
           ["vertical_integral_of_northward_heat_flux", "Vertical integral of northward heat flux"],
           ["vertical_integral_of_northward_kinetic_energy_flux", "Vertical integral of northward kinetic energy flux"],
           ["vertical_integral_of_northward_mass_flux", "Vertical integral of northward mass flux"],
           ["vertical_integral_of_northward_ozone_flux", "Vertical integral of northward ozone flux"],
           ["vertical_integral_of_northward_total_energy_flux", "Vertical integral of northward total energy flux"],
           ["vertical_integral_of_northward_water_vapour_flux", "Vertical integral of northward water vapour flux"],
           ["vertical_integral_of_potential_and_internal_energy", "Vertical integral of potential and internal energy"],
           ["vertical_integral_of_potential_internal_and_latent_energy",
            "Vertical integral of potential internal and latent energy"],
           ["vertical_integral_of_temperature", "Vertical integral of temperature"],
           ["vertical_integral_of_thermal_energy", "Vertical integral of thermal energy"],
           ["vertical_integral_of_total_energy", "Vertical integral of total energy"],
           ["vertically_integrated_moisture_divergence", "Vertically integrated moisture divergence"],
           ["volumetric_soil_water_layer_1", "Volumetric soil water layer 1"],
           ["volumetric_soil_water_layer_2", "Volumetric soil water layer 2"],
           ["volumetric_soil_water_layer_3", "Volumetric soil water layer 3"],
           ["volumetric_soil_water_layer_4", "Volumetric soil water layer 4"],
           ["wave_spectral_directional_width", "Wave spectral directional width"],
           ["wave_spectral_directional_width_for_swell", "Wave spectral directional width for swell"],
           ["wave_spectral_directional_width_for_wind_waves", "Wave spectral directional width for wind waves"],
           ["wave_spectral_kurtosis", "Wave spectral kurtosis"],
           ["wave_spectral_peakedness", "Wave spectral peakedness"],
           ["wave_spectral_skewness", "Wave spectral skewness"], ["zero_degree_level", "Zero degree level"]]
